---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /opt/docker_hub/registry
    server: 192.168.0.150
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-pvc
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteMany
---
