apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: docker
  name: docker
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30001
  selector:
    app: docker
  type: NodePort
status:
  loadBalancer: {}
